---
# tasks file for traefik_auth_proxy

# Make somewhere for config to live
- name: Create required paths
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    - "{{ proxy_config_dir }}"
    - "{{ proxy_config_dir }}/dynamic"
    - "{{ proxy_docker_dir }}"

# Generate a cookie secret/get it from file
- name: Create cookie signing secret
  become: true
  ansible.builtin.template:
    src: "cookie_secret.j2"
    dest: "{{ proxy_config_dir }}/cookie_secret"
    force: false  # Only set a secret if it doesn't exist
    mode: 0400

- name: Grab cookie signing secret from target
  become: true
  ansible.builtin.slurp:
    src: "{{ proxy_config_dir }}/cookie_secret"
  register: cookie_secret_data_slurped

- name: Set cookie secret fact
  ansible.builtin.set_fact:
    cookie_signing_secret: "{{ cookie_secret_data_slurped.content | b64decode }}"

# Template out config file for Traefik
- name: Create Traefik config file
  ansible.builtin.template:
    src: "traefik-static.yml.j2"
    dest: "{{ proxy_config_dir }}/traefik.yml"
    mode: 0640
  notify: restart_traefik

# Template out config file for Forward Auth
- name: Create Forward Auth config file
  ansible.builtin.template:
    src: "forward-auth.ini.j2"
    dest: "{{ proxy_config_dir }}/forward-auth.ini"
    mode: 0640
  notify: restart_traefik

# Template out Compose file
- name: Create docker-compose file
  ansible.builtin.template:
    src: "docker-compose.yml.j2"
    dest: "{{ proxy_docker_dir }}/docker-compose.yml"
    mode: 0644
  when: skip_launch is not defined

# Launch containers
- name: Start containers
  become: True
  community.docker.docker_compose:
    project_src: "{{ proxy_docker_dir }}"
    state: present
    project_name: "{{ proxy_compose_project }}"
  tags:
    - container_launch
  ignore_errors: "{{ ansible_check_mode }}"
  when: skip_launch is not defined
