---
- name: Generate config file
  hosts: localhost
  vars:
    # proxy_config_dir: /etc/traefik
    skip_launch: true
  tasks:
    - name: "Include traefik_auth_proxy"
      ansible.builtin.include_role:
        name: "traefik_auth_proxy"
