---
# handlers file for traefik_auth_proxy
- name: Restart containers on config change
  listen: restart_traefik
  become: True
  community.docker.docker_compose:
    project_src: "{{ proxy_docker_dir }}"
    project_name: "{{ proxy_compose_project }}"
    restarted: true
  ignore_errors: "{{ ansible_check_mode }}"
  when: skip_launch is not defined
