---
- name: Cleanup DNS entries
  hosts: all
  gather_facts: false
  tags:
    - cleanup
  vars:
    base_domain: "{{ lookup('ansible.builtin.env', 'BASE_DOMAIN') }}"
    temp_work_dir: "{{ lookup('ansible.builtin.env', 'TEMP_WORK_DIR') }}"
    desec_script: desec.py
  tasks:
    - name: Import cleanup tasks
      ansible.builtin.import_tasks: tasks/cleanup-dns.yml

- name: Cleanup containers
  hosts: all
  gather_facts: false
  tasks:
    - name: Stop demo containers
      community.docker.docker_container:
        name: "authproxy-site-{{ item }}"
        state: absent
      loop:
        - demo
        - secure
        - secure-two
      delegate_to: localhost

    - name: Stop OIDC mock server
      community.docker.docker_container:
        name: traefik_auth_proxy_molecule_oidc
        state: absent
      delegate_to: localhost

    - name: Stop proxy containers
      community.docker.docker_compose:
        project_src: /etc/traefik_proxy
        state: absent
        project_name: traefik_auth_proxy_molecule
        remove_volumes: true
      register: stop_proxy_containers
      # Ignore failures caused by the Compose file not existing.
      failed_when: stop_proxy_containers.failed == true and "Can't find a suitable configuration file" not in stop_proxy_containers.msg
      # Ignore errors because the container doesn't exist
      ignore_unreachable: true

    # Note that Ansible cannot empty a directory without removing it (or iterating the contents), so we have to use the shell
    - name: Remove config files from mounted directory  # noqa no-changed-when no-free-form
      ansible.builtin.shell: /bin/rm -rf /tmp/traefik_auth_proxy_molecule/*
      ignore_unreachable: true
