---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  # Ignore role name when linting
  ansible-lint -x 'role_name'
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # CAUTION: This gives the test container access to your underlying system
      # This is safe in CI because the VM is disposable, but be careful locally
      # Applies workaround to https://github.com/ansible-community/molecule/issues/1568
      - /var/run/docker.sock:/tmp/docker.sock
    command: ${MOLECULE_DOCKER_COMMAND:-""}  # systemd won't work if this is left to molecule's default
    pre_build_image: true
provisioner:
  name: ansible
scenario:
  name: default
