---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  # Ignore role name when linting
  ansible-lint -x 'role_name'
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /tmp/traefik_auth_proxy_molecule:/tmp/traefik_auth_proxy_molecule:rw
      # CAUTION: This gives the test container access to your underlying system
      # This is safe in CI because the VM is disposable, but be careful locally
      # Applies workaround to https://github.com/ansible-community/molecule/issues/1568
      - /var/run/docker.sock:/tmp/docker.sock
    command: ${MOLECULE_DOCKER_COMMAND:-""}  # systemd won't work if this is left to molecule's default
    pre_build_image: true
    network_mode: host
    etc_hosts:
      mock-oidc: 127.0.0.1
provisioner:
  name: ansible
  env:
    BASE_DOMAIN: ${BASE_DOMAIN:-ci-dns.samn.co.uk}
    RUN_TYPE: ${RUN_TYPE:-local}
    DESEC_TOKEN: ${DESEC_TOKEN}
scenario:
  name: default
