---
- name: Set up container to behave like a Docker host
  hosts: all
  become: true
  tasks:
    - name: Update apt cache (Ubuntu)
      ansible.builtin.apt:
        update_cache: true
      when: ansible_distribution == "Ubuntu"
    # Apply the Docker socket workaround in https://github.com/ansible-community/molecule/issues/1568
    - name: Link the docker socket
      ansible.builtin.file:
        src: /tmp/docker.sock
        dest: /var/run/docker.sock
        state: link
      changed_when: false
    - name: Install the docker module
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose
        state: present
