---
name: CI with Molecule
"on":
  push:
  pull_request:
  workflow_dispatch:
  # Build master every Thursday at 7AM (schedule only applies to the master branch)
  schedule:
    - cron: "0 7 * * 4"

defaults:
 run:
  working-directory: ./traefik_auth_proxy

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: traefik_auth_proxy  # Check out to where Ansible expects to find it
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Append GitHub Actions system path
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install lint dependencies.
        run: pip3 install ansible ansible-lint yamllint
      - name: Lint code.
        run: |
            yamllint .
            ansible-lint .
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      PY_COLORS: '1'
      ANSIBLE_FORCE_COLOR: '1'
      MOLECULE_DISTRO: ubuntu2004
      RUN_TYPE: ci
      DESEC_TOKEN: ${{ secrets.DESEC_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: traefik_auth_proxy  # Check out to where Ansible expects to find it
      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install deps
        run: pip3 install ansible ansible-lint 'molecule>=5.0.1' molecule-plugins[docker] dnspython

      - name: Create instances, prepare environment
        run: molecule create && molecule prepare
      - name: Apply the role to the instance
        run: molecule converge
      - name: Check the role is idempotent
        run: molecule idempotence
      - name: Run tests
        run: molecule verify
      - name: Print containers and logs for debugging
        if: failure()
        run: |
          docker ps;
          docker logs traefik_auth_proxy_molecule_reverse-proxy_1;
          docker logs traefik_auth_proxy_molecule_forward-auth_1;
          date

      - name: Clean up instance
        if: always()
        run: molecule cleanup && molecule destroy
