---
name: Cut a release
"on":
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to create (include the preceeding "v")'
        required: true
      description:
        description: 'Description to put in tag and release'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Create Tag and Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.description }}
          draft: false
          prerelease: false
      - name: Publish to Ansible Galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.galaxy_api_key }}

  push-config-generator:
    name: Push config-generator image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get datetime for tag
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYY-MM-DDTHHmmSS

      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: samdbmg
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: samdbmg/traefik_auth_proxy_config_generator
          tags: latest, ${{ steps.current-time.outputs.formattedTime }}, ${{ github.event.inputs.version }}
