---
name: Cut a release
"on":
  workflow_dispatch:
    inputs:
      version:
        description: 'New version to create (include the preceeding "v")'
        required: true
      description:
        description: 'Description to put in tag and release'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.tar.gz,foo/*.txt"
          body: ${{ github.event.inputs.description }}
          tag: ${{ github.event.inputs.version }}
          skipIfReleaseExists: true